In [1]:
import numpy as np

arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [2]:
import numpy as np

arr = np.linspace(5, 50, 10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [3]:
import numpy as np

my_list = [10, 20, 30, 40, 50]

arr = np.array(my_list)

print(arr)

[10 20 30 40 50]


In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reverse = arr[::-1]

print(reverse)

[50 40 30 20 10]


In [5]:
import numpy as np

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

first_row = arr[0, :]
last_column = arr[:, -1]

print("First row:", first_row)
print("Last column:", last_column)

First row: [1 2 3 4]
Last column: [ 4  8 12 16]


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

result = arr[:2, :2]

print(result)

[[1 2]
 [5 6]]


In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 5, 8])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)

print("Dot product:", dot_product)

Dot product: 32


In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)
median = np.median(arr)
standard_deviation = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", standard_deviation)

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
